dremio:
  auth:
    enabled: true
    username: "admin"
    password: "DremioSecretPassword123!"
    firstName: "Josh"
    lastName: "Yorko"
    email: "joshua.yorko@gmail.com"

  masterCoordinator:
    
    persistence:
      storageClass: "longhorn"
      size: 50Gi



  coordinator:
   
    persistence:
      storageClass: "longhorn"
      size: 50Gi

  executor:
      common:
        ## @param executor.common.replicaCount Number of Dremio Executor replicas to deploy
        ##
        replicaCount: 3
      persistence:
        storageClass: "longhorn"

      extraStartParams: >-
        -Xmx160g
        -XX:MaxDirectMemorySize=40g
        -XX:+UseG1GC
        -XX:G1HeapRegionSize=32M
        -XX:+UseGCOverheadLimit
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/opt/dremio/data/heap-dump.hprof

  defaultInitContainers:
    wait:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    generateConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    initCerts:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    copyDefaultConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    upgradeKeystore:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"

  service:
    type: LoadBalancer


minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "super_secret_minio_password"  # Change this to a secure password
  defaultBuckets: "dremio"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: LoadBalancer
    loadBalancerIP: ""
    ports:
      api: 9000
  resources:
    requests:
      memory: "6Gi"
      cpu: "2"
    limits:
      memory: "12Gi"
      cpu: "4"
  persistence:
    storageClass: "longhorn"
    size: 50Gi

zookeeper:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
  persistence:
    storageClass: "longhorn"
    size: 20Gi
