---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dremio-executor-default
  namespace: data-lakehouse
  labels:
    app.kubernetes.io/name: dremio
    app.kubernetes.io/instance: dremio
    app.kubernetes.io/part-of: dremio
    app.kubernetes.io/component: executor
    app.kubernetes.io/managed-by: Helm
    engine: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: dremio-executor-default
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70