dremio:
  auth:
    enabled: true
    username: kdlocpanda
    password: "jamisonVolvoMercedes724"
    firstName: Josh
    lastName: Yorko
    email: "joshua.yorko@gmail.com"

  masterCoordinator:
    persistence:
      storageClass: "longhorn"
      size: 50Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  coordinator:
    persistence:
      storageClass: "longhorn"
      size: 50Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  executor:
    persistence:
      storageClass: "longhorn"
      size: 200Gi
    extraStartParams: >-
      -Xmx160g
      -XX:MaxDirectMemorySize=40g
      -XX:+UseG1GC
      -XX:G1HeapRegionSize=32M
      -XX:+UseGCOverheadLimit
      -XX:+ExplicitGCInvokesConcurrent
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/opt/dremio/data/heap-dump.hprof
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  defaultInitContainers:
    wait:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    generateConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    initCerts:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    copyDefaultConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    upgradeKeystore:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"

  service:
    type: LoadBalancer

  extraVolumes:
    - name: dremio-tls
      secret:
        secretName: dremio-tls-secret

  extraVolumeMounts:
    - name: dremio-tls
      mountPath: /opt/dremio/tls
      readOnly: true

minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "jamisonVolvoMercedes724Minio"  # Change this to a secure password
  defaultBuckets: "dremio"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: LoadBalancer
    loadBalancerIP: ""
    ports:
      api: 9000
  resources:
    requests:
      memory: "6Gi"
      cpu: "2"
    limits:
      memory: "12Gi"
      cpu: "4"
  persistence:
    storageClass: "longhorn"
    size: 50Gi

zookeeper:
  enabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
  persistence:
    storageClass: "longhorn"
    size: 20Gi
