dremio:
  auth:
    enabled: true
    username: "admin"
    password: "super_secret_password"
    firstName: "Josh"
    lastName: "Yorko"
    email: "email@example.com"

  masterCoordinator:
    resources:
      requests:
        memory: "48Gi"
        cpu: "4"
      limits:
        memory: "60Gi"
        cpu: "6"
    persistence:
      storageClass: "gp2-expandable"
      size: 50Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  coordinator:
    resources:
      requests:
        memory: "24Gi"
        cpu: "4"
      limits:
        memory: "48Gi"
        cpu: "6"
    persistence:
      storageClass: "gp2-expandable"
      size: 50Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password
    autoscaling:
      hpa:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPU: 80
        targetMemory: 80

  executor:
    common:
      resources:
        requests:
          memory: "160Gi"
          cpu: "10"
        limits:
          memory: "300Gi"
          cpu: "18"
      persistence:
        storageClass: "gp2-expandable"
        size: 200Gi
      extraStartParams: >-
        -Xmx160g
        -XX:MaxDirectMemorySize=40g
        -XX:+UseG1GC
        -XX:G1HeapRegionSize=32M
        -XX:+UseGCOverheadLimit
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/opt/dremio/data/heap-dump.hprof
        -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
        -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
      extraEnvVars:
        - name: DREMIO_TLS_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dremio-keystore-password
              key: password
      autoscaling:
        hpa:
          enabled: true
          minReplicas: 1
          maxReplicas: 5
          targetCPU: 80
          targetMemory: 80

  defaultInitContainers:
    wait:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    generateConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    initCerts:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    copyDefaultConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    upgradeKeystore:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"

  service:
    type: LoadBalancer

  extraVolumes:
    - name: dremio-tls
      secret:
        secretName: dremio-tls-secret

  extraVolumeMounts:
    - name: dremio-tls
      mountPath: /opt/dremio/tls
      readOnly: true

minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "super_secret_minio_password"  # Change this to a secure password
  defaultBuckets: "dremio"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: LoadBalancer

    ports:
      api: 9000
  resources:
    requests:
      memory: "6Gi"
      cpu: "2"
    limits:
      memory: "12Gi"
      cpu: "4"
  persistence:
    storageClass: "gp2-expandable"
    size: 50Gi

zookeeper:
  enabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
  persistence:
    storageClass: "gp2-expandable"
    size: 20Gi
