dremio:
  auth:
    enabled: true
    username: admin
    password: "Pa22word"
    firstName: Josh
    lastName: Yorko
    email: "email@example.com"

  masterCoordinator:
    persistence:
      storageClass: "standard"
      size: 8Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  coordinator:
    persistence:
      storageClass: "standard"
      size: 8Gi
    extraStartParams: >-
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  executor:
    persistence:
      storageClass: "standard"
      size: 8Gi
    extraStartParams: >-
      -XX:+UseG1GC
      -XX:+UseGCOverheadLimit
      -XX:+ExplicitGCInvokesConcurrent
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/opt/dremio/data/heap-dump.hprof
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    extraEnvVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password

  defaultInitContainers:
    wait:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    generateConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    initCerts:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    copyDefaultConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    upgradeKeystore:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"

  service:
    type: ClusterIP

  extraVolumes:
    - name: dremio-tls
      secret:
        secretName: dremio-tls-secret

  extraVolumeMounts:
    - name: dremio-tls
      mountPath: /opt/dremio/tls
      readOnly: true

minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "Pa22word"  # Change this to a secure password
  defaultBuckets: "dremio"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: ClusterIP
    #loadBalancerIP: ""
    ports:
      api: 9000
  #resources:
  #  requests:
  #    memory: "6Gi"
  #    cpu: "2"
  #  limits:
  #    memory: "12Gi"
  #    cpu: "4"
  persistence:
    storageClass: "standard"
    size: 100Gi

zookeeper:
  enabled: true
  replicaCount: 1
  #resources:
  #  requests:
  #    cpu: "1"
  #    memory: "3Gi"
  #  limits:
  #    cpu: "2"
  #    memory: "6Gi"
  persistence:
    storageClass: "standard"
    size: 15Gi
