global:
  defaultStorageClass: "longhorn"

dremio:
  auth:
    enabled: true
    username: "admin"
    password: "Pa22word"
    firstName: "Josh"
    lastName: "Yorko"
    email: "joshua.yorko@gmail.com"

masterCoordinator:
  persistence:
    size: 8Gi
    storageClass: "longhorn"
  extraStartParams: >-
    -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
    -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
  envVars:
    - name: DREMIO_TLS_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dremio-keystore-password
          key: password

coordinator:
  persistence:
    size: 8Gi
    storageClass: "longhorn"
  extraStartParams: >-
    -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
    -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
  envVars:
    - name: DREMIO_TLS_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dremio-keystore-password
          key: password

executor:
  common:
    persistence:
      size: 8Gi
      storageClass: "longhorn"
    extraStartParams: >-
      -Xmx12g                         
      -XX:MaxDirectMemorySize=8g      
      -XX:+UseG1GC
      -XX:G1HeapRegionSize=32M
      -XX:+UseGCOverheadLimit
      -XX:+ExplicitGCInvokesConcurrent
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/opt/dremio/data/heap-dump.hprof
      -Ddremio.tls.keyStore=/opt/dremio/tls/dremio.jks
      -Ddremio.tls.keyStorePassword=${DREMIO_TLS_KEYSTORE_PASSWORD}
    envVars:
      - name: DREMIO_TLS_KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dremio-keystore-password
            key: password
    #autoscaling:
    #  hpa:
    #    enabled: true
    #    minReplicas: 3
    #    maxReplicas: 5
    #    targetCPU: 75
    #    targetMemory: 80

  engines:
    - name: data-science
      overrides:
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        podLabels:
          workload: "data-science"
    - name: analytics
      overrides:
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        podLabels:
          workload: "analytics"

initContainers:
  - name: copy-default-conf
  - name: generate-conf
  - name: init-certs
  - name: set-keystore-permissions
    image: busybox
    command: ['sh', '-c', 'chown -R 1001:1001 /opt/dremio/tls && chmod -R 600 /opt/dremio/tls/*']
    volumeMounts:
      - name: dremio-tls
        mountPath: /opt/dremio/tls
  - name: setup-tls
    image: busybox
    command: ['sh', '-c', 'mkdir -p /opt/dremio/tls && cp /tls-secret/dremio.jks /opt/dremio/tls/dremio.jks && chmod 600 /opt/dremio/tls/dremio.jks && chown 1001:1001 /opt/dremio/tls/dremio.jks']
    volumeMounts:
      - name: dremio-tls
        mountPath: /tls-secret
      - name: tls-dir
        mountPath: /opt/dremio/tls
service:
  type: LoadBalancer

extraVolumes:
  - name: dremio-tls
    secret:
      secretName: dremio-tls-secret
  - name: tls-dir
    emptyDir: {}
extraVolumeMounts:
  - name: dremio-tls
    mountPath: /opt/dremio/tls
    readOnly: true
  - name: tls-dir
    mountPath: /opt/dremio/tls

extraEnvVars:
  - name: DREMIO_TLS_KEYSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dremio-keystore-password
        key: password

minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "Pa22word22"
  defaultBuckets: "dremio,warehouse,upload"
  provisioning:
    enabled: true
    extraCommands: 
      - "mc anonymous set download provisioning/dremio"
      - "mc anonymous set download provisioning/warehouse"
      - "mc anonymous set download provisioning/upload"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: LoadBalancer
    loadBalancerIP: ""
    ports:
      api: 9000
  persistence:
    storageClass: "longhorn"
    size: 50Gi

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    storageClass: "longhorn"
    size: 8Gi
