dremio:
  auth:
    enabled: true
    username: "admin"
    password: "super_secret_password"
    firstName: "Josh"
    lastName: "Yorko"
    email: "email@example.com"

  masterCoordinator:
    resources:
      requests:
        memory: "16Gi"
        cpu: "4"
      limits:
        memory: "36Gi"
        cpu: "6"
    persistence:
      
      size: 50Gi

  coordinator:
    resources:
      requests:
        memory: "16Gi"
        cpu: "4"
      limits:
        memory: "36Gi"
        cpu: "6"
    persistence:
      
      size: 50Gi

  executor:
    common:
      resources:
        requests:
          memory: "32Gi"
          cpu: "4"
        limits:
          memory: "32Gi"
          cpu: "8"
      persistence:
        
        size: 100Gi

  defaultInitContainers:
    wait:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    generateConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    initCerts:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    copyDefaultConf:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
    upgradeKeystore:
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:833662972458:certificate/d5350613-9506-4d64-af34-21b55ba5cc28"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

minio:
  enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "MinioPassword123!"  # Change this to a secure password
  defaultBuckets: "dremio"
  tls:
    enabled: false
    autoGenerated: false
  service:
    type: LoadBalancer
    loadBalancerIP: ""
    ports:
      api: 9000
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"
  persistence:
    
    size: 50Gi

zookeeper:
  enabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  persistence:
    
    size: 20Gi
