apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-datalakehouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshyorko/open-datalakehouse.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true