apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiam9zaHlvcmtvIiwicGFzc3dvcmQiOiJnaHBfdUZpaEwwdGxMVEYwSzRNQlFZYWJPQkFObjFhb1lpMG9uQWJiIiwiZW1haWwiOiJqb3NodWEueW9ya29AZ21haWwuY29tIiwiYXV0aCI6ImFtOXphSGx2Y210dk9tZG9jRjkxUm1sb1REQjBiRXhVUmpCTE5FMUNVVmxoWWs5Q1FVNXVNV0Z2V1drd2IyNUJZbUk9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-login
  namespace: data-lakehouse
type: kubernetes.io/dockerconfigjson
