---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-data
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Static provisioning (no StorageClass)
  hostPath:
    path: "/mnt/data/notebook"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-data
  namespace: data-lakehouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""  # Must match the PV's storageClassName
  volumeName: notebook-data  # Binds to the specified PV
