apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook
  namespace: data-lakehouse
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

  storageClassName: "longhorn"
  hostPath:
    path: "/mnt/data/notebook"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-data
  namespace: data-lakehouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: "longhorn"
  volumeName: notebook
