---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-login
  namespace: data-lakehouse
spec:
  encryptedData:
    .dockerconfigjson: AgAk0XlbEXxKtDqqu0hYwX7k8+glgDqnCta4iuSTtnOzAkMWJJgOTV8rRPIrYiXH8q0q+y1B4hgYrlbb82187dTACcCOlkebV/DumNmCDfM+jGuuDEbg90ns67bBeSVxypJI5CV4gPsdYTvBDNOWag4y133MhrUE7ft3c3olEzS6WZbbsmm3oJ+tG6scUOnhQo1bI8NSt4u4AoLL+BeJCLitXkVJiB9C7HwXmKOgXIK+MDWpI8WaudFmQ4N489Acdiu4F6fYh1bEmsNwreHveHv4Mp+MnjVDY5ImX5CEvspV2ZFtlQvcqqGInG8XAtaef+q0Bug3LMIK/gJGA9cPv0QYIsrmsKOTV96/f04KCh0Z7vr4Ju8ClKqgpjJtxU5zTESw4NoPtLKTIHnnRWTdTcJtU9tQsS+Z1cbdxDeobRj8YWvAkxZkNUNeA7f6qM/5HhIpxuCylhB043tfGgVXNBbIRKMtH8Po3YGL8bnM6vYwlcd8dxO6DlnnJgGKAAl84e/oBHIIERhVbAUvFHk5POoqP9iQ4MkrQQZNOufkRVvfwSzVBLJwa5lRf58F8hIP0d+uI6//rTCi9iu2rLy46gSF+BqH0irA89PWP3TTkqNU5EZ8IWKZCyKKKl9sLkJGNbEozMQAFEHUwODwB4DmZZ+Xv6C/+w5oHkt9E4u87pgUpYn2H/smSEuPvuwd8U2YCc0JIZClSCKU1vlTB/vxYPkQnHT10H4hZVs0q0oguzYJSAsOUevJ2zGZWpFpAfCQd4xwFHEuX6EOf0Gfw+xM7qyEVN0jXaFRNhPu6xuE3SfS919rZMpGp0At+7hKEBNfi6dmh87SHud6O2PM2/QUcS6RMIrqHT1hyWhPHGeabBEh9dDFHisgVi1orKZK63S7o3zZi9zAKZE5WsMesOBow619GTMw9io3pu3rGoPXH4SyDBROI6+3II86xgk4BJ6PbuWkffPVT0Wr5K5+YaoVuUG/tMc2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-login
      namespace: data-lakehouse
    type: kubernetes.io/dockerconfigjson
