---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-login
  namespace: data-lakehouse
spec:
  encryptedData:
    .dockerconfigjson: AgCcug6O/H8KGBuzEnPWn7T7ZUbpTstxMckoTuweJaCZr4pDdazB6XibZSumsLJOYU1itKS6LGYC4QnuF6dUdfh6PpW2NOGbwbqY7bV+fERpDdwqDGtMQW0tvhpLoUD+wstnvJVXhA1ueDVQ5XgzKF1Y0ccXZ1B9eYsP2j4zVIZeO6cAYmszrbEBT7dnP34S62WDdKt6NkGzC+v2LbH6C79BPzsav1qBPN4dhg0o86FC0Hv45KRhbRp9S3eQltBfIgrUIRzWb/QE4fnS6VH0SXOVW4PTUed6qrY+vQR4IDVCbrwEGolGDSvmy1vv0Gj0TnC09oL6LpG1IHllO7KveTjUBHla1D9GgDW/8Yo+YE5fH1dbFQbeWJQvzkaEHrFKjWcGd02O522kJ3/2yesxgcaoimtyGNE5DII49Go2cw2oOCkrUMpAzt6Tgtg5L2PSpnmA0agnUO70WKJd00Zk3ddKcxScvn9/HKkZ8mzX7Ta+1jIHMpt9EzM9gEfyTyx/Q7xgFAUJg3aSySBwPCrpqKTAe9YCAKvdPHWOtfMHrjC2nRRNiLVHpjZ6jVrsCqPmpHNJh94zYwbRG+HGrpOIOvNh37mC58o535vie8z5T8yMgcSgF3xDfAa5pNYXDMwnBHzK+xOtEjnkoIh182oQpaP+xzYO7CfSzh35ZkWSqvKCzv3DJeAIdQ+LkKgh7KW0rfAN7o0wvBYFDQkftEB/DI8VQidOhO8z6SBPL2EfbtoH1AwyPX5pRJKndOtYZjiK2J1PBtICBKTfasZuII/oiVoy0j9UG1vxi58tXNFXKCID+y/oZ7RsUvCfPXTPZV/LCb1fuACNrRKd6fSGwAmOLtmjoTZG3DFp5yE79HZxnG3NjUZu1wk0GLmr3efdY+vWUUDsrg2PcZMQBwHGLp9lLMsPBeyXDV3heRRk84a3P04I/U86rLKgm9ZhCBQG9Lii5w/B/s0vrR0tVksQqQ0TSnmrKmfr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-login
      namespace: data-lakehouse
    type: kubernetes.io/dockerconfigjson
