---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-login
spec:
  encryptedData:
    .dockerconfigjson: AgANaW/wUZN4todoqOy9T1sIBaUQh71CU2R2xHs0A8h3O4+JfD3PR8UwFGf2p5qVF43SA5J4e3kHurgguMPS9YfN+cqU/PBWLwaMELKN8UTYwtnvGozkr8qfzH6d8IZj4imIoHUOZxIpEhHgldG1I0RKU5pbM4K9dkvygXfXzyZnR+tsEgEPH0BbkUvPPR9fLC2dAwu6uWSoodQaBWeI0LQ2liYtgtSJmJFEN7X7/fpPg9bAaus8GBov96HUzr2uYdFYNUKqBTv1Jkgt3x+TADOFSaATTgkB6mQ+/AYRjqq59KI5x+Y2RS950Qagq+GELwb0dOe3MnwI1M51mxPUsIM+QyEwwDYtaqvxF7Y0niiTcK1zPFPGx+xgOWqZH/a6IEvC2xd29B8X5SDpY/HW0GoQd2NNzS+RyQ3MTJ+X5Tc5pTaVH7br9FE7CzPvDsUGGQNL6tRCqhad9WreFjP15ioM5eYJcQA5piEpAyZDYkhtGWv2UirxK6iSpzDLhH5hRyqcPqyfO7rwHeFMBCJ2sguwNmv9Jx5JQeNtDw3NvbUqp26kjSNp8iprAXCpeJmtuJ17goJ3lKmm/0OunGi+urxFlwsABq6/GQMlH821FbW1V5FwHlJJnoTRbxpPHGvdBTT9PT/vEansYiUL44k0r0ipF8PsJro6cXms7AYnJRM6YPoV1d92BbrcV8isAyazFa+59ZowVmQNCFPVfUHCFp6MqssD8mIvD7Gf5gYZfvxLr1/0eg7WSTtPxqxWiDOCPr6nsnLIK3yWn4PFMDonnP5WlbjArftpcCeN+zvYw5RFIvTawZ7CY3MDq2ZjvapNQ4ObfPfy2SquWmcy7ovMkA8AK1AEFnLEQRW/H+35Oj+5rvVPg36DM7ZzlgzQljREKPzGHucsxHQKhODpIJdn0r7kKVXKc4v7gbj4NznDiNwJURZDKEpB4/z54dx/lH/E+FYk9XKONBhHtrXpwzGTZ5Taw2v4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-login
    type: kubernetes.io/dockerconfigjson
