apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  namespace: data-lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spark
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /home/docker/work"]
          volumeMounts:
            - mountPath: /home/docker/work
              name: notebook-data
      containers:
        - image: jedock87/datalake-spark:latest
          name: spark
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              protocol: TCP
    
          volumeMounts:
            - mountPath: /home/docker/work
              name: notebook-data
      volumes:
        - name: notebook-data
          persistentVolumeClaim:
            claimName: notebook-data
