apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-pv
  namespace: data-lakehouse
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  
  hostPath:
    path: "/mnt/data/notebook"
    type: DirectoryOrCreate
  
