apiVersion: v1
kind: Service
metadata:
  name: spark
  namespace: data-lakehouse
spec:
  type: ClusterIP
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: spark
