name: dremio-laptop-lakehouse


services:


  spark_notebook:
      image: jedock87/datalake-spark:latest
      build:
        context: .
        dockerfile: notebooks/Dockerfile
      container_name: notebook
      volumes:
        - notebook-pv:/home/jovyan/work
      networks:
        dremio-laptop-lakehouse:
      ports: 
        - "8888:8888"  # Notebook


networks:
  dremio-laptop-lakehouse:
  # Spark Notebook
 
volumes:
  notebook-pv:
    driver: local
