# Use the Dremio OSS image as the base
FROM dremio/dremio-oss:latest

# Copy dremio.conf from the host to the container
COPY dremio.conf /opt/dremio/conf/dremio.conf

# Copy core-site.xml from the host to the container
COPY core-site.xml /opt/dremio/conf/core-site.xml