name: dremio-laptop-lakehouse


services:
  # Nessie Catalog Server Using In-Memory Store
  catalog:
    image: projectnessie/nessie:latest
    container_name: catalog
    networks:
      dremio-laptop-lakehouse:
    ports:
      - 19120:19120

  # Minio Storage Server
  storage:
    image: minio/minio:latest
    container_name: storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      dremio-laptop-lakehouse:
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  
  # Minio Setup for creating buckets
  minio-setup:
    image: minio/mc:latest
    depends_on:
      - storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to start...' &&
      /bin/sleep 10 &&
      mc alias set minio http://storage:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD &&
      mc mb minio/warehouse &&
      mc mb minio/dremiostorage &&
      echo 'Buckets created.'"
    networks:
      dremio-laptop-lakehouse:

  # Dremio
  dremio:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: DOCKERFILE
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio
    depends_on:
      - minio-setup
    networks:
      dremio-laptop-lakehouse:

  spark_notebook:
      image: jedock87/datalake-spark:latest
      container_name: notebook
      volumes:
        - notebook-pv:/home/jovyan/work
      networks:
        dremio-laptop-lakehouse:
      ports: 
        - "8888:8888"  # Notebook


networks:
  dremio-laptop-lakehouse:
  # Spark Notebook
 
volumes:
  notebook-pv:
    driver: local
