services:

  # Spark Notebook
  spark_notebook:
    image: jedock87/datalake-spark:latest
    build: .
    container_name: notebook
    volumes:
      - notebook-pv:/home/jovyan/work
    networks:
      dremio-spark:
    ports: 
      - "8888:8888"  # Notebook

volumes:

  notebook-pv:


networks:
  dremio-spark:
