# Configuration values for the Nessie application Helm chart
global:


  storageClass: ""

replicaCount: 1
# Specify any additional configuration values for the Nessie application
# For example:
# configKey: configValue
