# Configuration values for the Nessie application Helm chart
global:
  storageClass: "longhorn"

replicaCount: 1

# Nessie service configuration
service:
  server:
    type: ClusterIP

# Nessie Configuration Overrides
configOverrides:
  nessie:
    catalog:
      default-warehouse: "warehouse"
      warehouses:
        warehouse:
          location: "s3://warehouse/"
      service:
        s3:
          default-options:
            endpoint: "http://dremio-minio:9000/"
            access-key: "minio-admin"
            secret-key: "Pa22word22"
            path-style-access: "true"
            region: "us-east-1"
    server:
      authentication:
        enabled: "false"
