# Configuration values for the Nessie application Helm chart
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []

  storageClass: "longhorn"

replicaCount: 1
# Specify any additional configuration values for the Nessie application
# For example:
# configKey: configValue