apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
	repoURL: https://github.com/open-datalakehouse/application-charts
	targetRevision: HEAD
	path: cert-manager
  destination:
	server: https://kubernetes.default.svc
	namespace: data-lakehouse
  syncPolicy:
	automated:
	  prune: true
	  selfHeal: true