apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: dremio
    targetRevision: 0.1.13 # Adjust version as needed
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/joshyorko/open-datalakehouse/main/application-charts/dremio/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: data-lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true