apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nessie
    targetRevision: 0.1.26  # Adjust version as needed
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/joshyorko/open-datalakehouse/main/application-charts/nessie/nessie-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data-lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true