apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nessie
    targetRevision: 1.0.0  # Adjust version as needed
    helm:
      parameters:
        - name: valueFiles
          value: |
            # Fetch values.yaml from GitHub
            - https://github.com/joshyorko/open-datalakehouse/raw/main/application-charts/nessie/nessie-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data-lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true