apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.8.3  # Adjust version as needed
    helm:
      parameters:
        - name: valueFiles
          value: |
            # Fetch values.yaml from GitHub
            - https://github.com/joshyorko/open-datalakehouse/raw/main/path/to/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data-lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
